language: java
install: true
dist: trusty

jdk:
  - oraclejdk8

before_install:
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3CB3BD13
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
 - chmod +x gradlew
 
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-fonts-extra
    
script:
  - ./gradlew jar 

