package org.jvoicexml.eclipse.debug.ui.launching;

/*
 * JVoiceXML VTP Plugin
 *
 * Copyright (C) 2008 Dirk Schnelle-Walka
 *
 * Copyright (c) 2008 Dirk Schnelle-Walka
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */


/**
 * Class to communicate dialog events from a VoiceXML Browser to any Eclipse
 * listener.
 * 
 * @author Dirk Schnelle-Walka
 */
public class VoiceXMLDialogMessage {
    /**
     * The participant.
     */
    protected String participant;

    /**
     * Log dialog message generated by the VoiceXML Browser
     */
    protected String message;

    /**
     * Creates a new VoiceXMLLogMessage object.
     * 
     * @param date
     *            The date the event occurred.
     * @param message
     *            The content of the event.
     */
    public VoiceXMLDialogMessage(String participant, String message) {
        setParticipant(participant);
        setMessage(message);
    }

    /**
     * Returns the participant.
     * 
     * @return the participant.
     */
    public String getParticipant() {
        if (participant == null) {
            return "(unknown)";
        }
        return participant;
    }

    /**
     * Sets the participant.
     * 
     * @param participant
     *            the participant.
     */
    public void setParticipant(String participant) {
        this.participant = participant;
    }

    /**
     * Returns the message contained in the event.
     * 
     * @return The message contained in the event. Will not be null.
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the message in the event.
     * 
     * @param message
     *            The message the event should contain.
     */
    public void setMessage(String message) {
        if (message == null) {
            message = ""; //$NON-NLS-1$
        }
        this.message = message;
    }
}
