//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.14 at 08:23:58 PM CET 
//

package org.jvoicexml.mmi.events;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{http://www.w3.org/2008/04/mmi-arch}group.allEvents.attrib"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "CancelRequest")
public class CancelRequest extends LifeCycleRequest implements Serializable {
    /** The serial version UID. */
    private static final long serialVersionUID = 6942351085394497980L;
    protected List<Object> data;

    @XmlElementWrapper(name = "Data")
    public List<Object> getData() {
        if (data == null) {
            data = new ArrayList<Object>();
        }
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *            allowed object is {@link AnyComplexType }
     * 
     */
    public void setData(final List<Object> value) {
        this.data = value;
    }

}
