//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.15 at 03:35:15 PM CEST 
//


package org.jvoicexml.mmi.events.eclipse;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jvoicexml.mmi.events.eclipse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StatusInfo_QNAME = new QName("http://www.w3.org/2008/04/mmi-arch", "statusInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jvoicexml.mmi.events.eclipse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewContextRequest }
     * 
     */
    public NewContextRequest createNewContextRequest() {
        return new NewContextRequest();
    }

    /**
     * Create an instance of {@link AnyComplexType }
     * 
     */
    public AnyComplexType createAnyComplexType() {
        return new AnyComplexType();
    }

    /**
     * Create an instance of {@link ClearContextResponse }
     * 
     */
    public ClearContextResponse createClearContextResponse() {
        return new ClearContextResponse();
    }

    /**
     * Create an instance of {@link CancelRequest }
     * 
     */
    public CancelRequest createCancelRequest() {
        return new CancelRequest();
    }

    /**
     * Create an instance of {@link PauseRequest }
     * 
     */
    public PauseRequest createPauseRequest() {
        return new PauseRequest();
    }

    /**
     * Create an instance of {@link NewContextResponse }
     * 
     */
    public NewContextResponse createNewContextResponse() {
        return new NewContextResponse();
    }

    /**
     * Create an instance of {@link ExtensionNotification }
     * 
     */
    public ExtensionNotification createExtensionNotification() {
        return new ExtensionNotification();
    }

    /**
     * Create an instance of {@link PrepareResponse }
     * 
     */
    public PrepareResponse createPrepareResponse() {
        return new PrepareResponse();
    }

    /**
     * Create an instance of {@link PrepareRequest }
     * 
     */
    public PrepareRequest createPrepareRequest() {
        return new PrepareRequest();
    }

    /**
     * Create an instance of {@link ContentURLType }
     * 
     */
    public ContentURLType createContentURLType() {
        return new ContentURLType();
    }

    /**
     * Create an instance of {@link Mmi }
     * 
     */
    public Mmi createMmi() {
        return new Mmi();
    }

    /**
     * Create an instance of {@link ClearContextRequest }
     * 
     */
    public ClearContextRequest createClearContextRequest() {
        return new ClearContextRequest();
    }

    /**
     * Create an instance of {@link CancelResponse }
     * 
     */
    public CancelResponse createCancelResponse() {
        return new CancelResponse();
    }

    /**
     * Create an instance of {@link DoneNotification }
     * 
     */
    public DoneNotification createDoneNotification() {
        return new DoneNotification();
    }

    /**
     * Create an instance of {@link PauseResponse }
     * 
     */
    public PauseResponse createPauseResponse() {
        return new PauseResponse();
    }

    /**
     * Create an instance of {@link ResumeRequest }
     * 
     */
    public ResumeRequest createResumeRequest() {
        return new ResumeRequest();
    }

    /**
     * Create an instance of {@link ResumeResponse }
     * 
     */
    public ResumeResponse createResumeResponse() {
        return new ResumeResponse();
    }

    /**
     * Create an instance of {@link StartRequest }
     * 
     */
    public StartRequest createStartRequest() {
        return new StartRequest();
    }

    /**
     * Create an instance of {@link StartResponse }
     * 
     */
    public StartResponse createStartResponse() {
        return new StartResponse();
    }

    /**
     * Create an instance of {@link StatusRequest }
     * 
     */
    public StatusRequest createStatusRequest() {
        return new StatusRequest();
    }

    /**
     * Create an instance of {@link StatusResponse }
     * 
     */
    public StatusResponse createStatusResponse() {
        return new StatusResponse();
    }

    /**
     * Create an instance of {@link ContentType }
     * 
     */
    public ContentType createContentType() {
        return new ContentType();
    }

    /**
     * Create an instance of {@link EmmaType }
     * 
     */
    public EmmaType createEmmaType() {
        return new EmmaType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2008/04/mmi-arch", name = "statusInfo")
    public JAXBElement<AnyComplexType> createStatusInfo(AnyComplexType value) {
        return new JAXBElement<AnyComplexType>(_StatusInfo_QNAME, AnyComplexType.class, null, value);
    }

}
