/*
 * File:    $RCSfile: StreamingTerminal.java,v $
 * Version: $Revision: 1.3 $
 * Date:    $Date: 2006/05/16 07:26:21 $
 * Author:  $Author: schnelle $
 * State:   $State: Exp $
 *
 * JVoiceXML - A free VoiceXML implementation.
 *
 * Copyright (C) 2005 JVoiceXML group - http://jvoicexml.sourceforge.net
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

package org.jvoicexml.implementation.telephony;

import java.io.InputStream;
import java.io.OutputStream;

/**
 * A Terminal represents a telephony endpoint managed by a JVoiceXML
 * provider - i.e. It is the line that a person calls to interact with a
 * VoiceXML application.<br/>
 * Streaming terminals play outgoing audio streams (i.e. Audio
 * generated by a VoiceXML application) via their output stream
 * and record incoming audio (i.e. Spoken or DTMF commands) via their
 * input stream.
 *
 * @author Davide Bruzzone
 * @since 0.3
 */
public interface StreamingTerminal
        extends Terminal {
    /**
     * Returns the terminal's input stream. Streaming terminals record
     * incoming audio (i.e. Spoken or DTMF commands) via their
     * input stream.
     *
     * @return The terminal's input stream
     */
    InputStream getInputStream();

    /**
     * Sets the terminal's input stream.  Streaming terminals record
     * incoming audio (i.e. Spoken or DTMF commands) via their
     * input stream.
     *
     * @param inputStream The terminal's input stream
     */
    void setInputStream(InputStream inputStream);

    /**
     * Returns the terminal's output stream. Streaming terminals play
     * outgoing audio streams (i.e. Audio generated by a VoiceXML
     * application) via their output stream.
     *
     * @return The terminal's output stream
     */
    OutputStream getOutputStream();

    /**
     * Sets the terminal's output stream. Streaming terminals play
     * outgoing audio streams (i.e. Audio generated by a VoiceXML
     * application) via their output stream.
     *
     * @param outputStream The terminal's output stream
     */
    void setOutputStream(OutputStream outputStream);
}
