/*
 * File:    $HeadURL$
 * Version: $LastChangedRevision$
 * Date:    $Date$
 * Author:  $LastChangedBy$
 *
 * JVoiceXML - A free VoiceXML implementation.
 *
 * Copyright (C) 2006-2014 JVoiceXML group - http://jvoicexml.sourceforge.net
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Library General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Library General Public License for more details.
 *
 *  You should have received a copy of the GNU Library General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */
package org.jvoicexml.talkinghead.view;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * Talking Head window, which shows the Avatar.
 * 
 * @author Matthias Mettel
 * @author Markus Ermuth
 * @author Alex Krause
 * 
 * @version $LastChangedRevision$
 * @since 0.7.3
 */
public class AvatarViewer extends JFrame {
  /**
   * Default width value for the viewer. 
   */
  public static final int DEFAULT_FRAME_WIDTH = 640;
  
  /**
   * Default height value for the viewer. 
   */
  public static final int DEFAULT_FRAME_HEIGHT = 480;
  
  /**
   * Default Serial Version, for Serialization (generated by Eclipse).
   */
  private static final long serialVersionUID = 1L;

  /**
   * Image Panel to display the Avatar.
   */
  private JImagePanel avatarDisplay;
  
  /**
   * Panel for the Status Display Labels.
   */
  private JPanel statusPanel;
  
  /**
   * Displays the Speech Output, when MaryTTS isn't working.
   */
  private JLabel speechDisplay;
  
  /**
   * Displays the Status of the TalkingHead.
   */
  private JLabel statusDisplay;
  
  /**
   * Constructor, which sets up the GUI.
   */
  public AvatarViewer() {    
    //Add Avatar Display to the FrameCenter
    avatarDisplay = new JImagePanel();
    getContentPane().add(avatarDisplay, BorderLayout.CENTER);
    
    //Initize Status Panel
    statusPanel = new JPanel();
    statusPanel.setLayout(new GridLayout(2, 1));
    getContentPane().add(statusPanel, BorderLayout.SOUTH);
    
    //Add Speech Display
    speechDisplay = new JLabel("Speech: ");
    statusPanel.add(speechDisplay);
    
    //Add Status Display
    statusDisplay = new JLabel("Status:");
    statusPanel.add(statusDisplay);
    
    //Set Frame Data
    this.setTitle("TalkingHead");
    this.setBounds(0, 0, DEFAULT_FRAME_WIDTH, DEFAULT_FRAME_HEIGHT);
  }
  
  /**
   * Sets the Image of the Avatar Display.
   * 
   * @param img Avatar Image, which will be displayed
   */
  public final void setAvatarDisplay(final Image img) {
    avatarDisplay.setImage(img);
  }
  
  /**
   * Sets the Text of the current Speech.
   * 
   * @param speech text of the speech
   */
  public final void setSpeechDisplay(final String speech) {
    speechDisplay.setText(speech);
  }
  
  /**
   * Sets the text of the status Display.
   * 
   * @param status Text, which shows the current status of the Avatar
   */
  public final void setStatusDisplay(final String status) {
    statusDisplay.setText(status);
  }
}
