/*
 * File:    $HeadURL$
 * Version: $LastChangedRevision$
 * Date:    $Date$
 * Author:  $LastChangedBy$
 *
 * JVoiceXML - A free VoiceXML implementation.
 *
 * Copyright (C) 2008 JVoiceXML group - http://jvoicexml.sourceforge.net
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Library General Public
 *  License as published by the Free Software Foundation; either
 *  version 2 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Library General Public License for more details.
 *
 *  You should have received a copy of the GNU Library General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

package org.jvoicexml;

/**
 * Information about a phone that was generated by the synthesizer.
 *
 * @author Renato Cassaca
 * @version $Revision$
 */
public final class SpeakablePhoneInfo {
    /** The generated phoneme. */
    private final String phoneme;

    /** The duration of the phoneme. */
    private final int duration;

    /**
     * Constructs a new object.
     * @param phone the generated phoneme.
     * @param dur the duration of the phoneme.
     */
    public SpeakablePhoneInfo(final String phone, final int dur) {
        phoneme = phone;
        duration = dur;
    }

    /**
     * Retrieves the phoneme.
     * @return the phoneme.
     */
    public String getPhoneme() {
        return phoneme;
    }

    /**
     * Retrieves the duration of the phoneme.
     * @return duration of the phoneme.
     */
    public int getDuration() {
        return duration;
    }
}
